DEBUG = false

SQLALCHEMY_TRACK_MODIFICATIONS = true
SESSION_COOKIE_SAMESITE="Lax"

# Security
# ========

SECRET_KEY = "my_very_secret_key"

## If you serve your app over https, set these cookie-parameters to true
# SESSION_COOKIE_SECURE = true
# REMEMBER_COOKIE_SECURE = true


# Authentication
# ==============

## enable authentication, enabled by default since asreview version 1.6+
# LOGIN_DISABLED = false

ALLOW_ACCOUNT_CREATION = true
SECURITY_PASSWORD_SALT = "abCDefGH"
# EMAIL_VERIFICATION = true


# Email server
# ============

# MAIL_SERVER = "smtp.sendgrid.net"
# MAIL_PORT = 465
# MAIL_USE_TLS = false
# MAIL_USE_SSL = true
# MAIL_USERNAME = "apikey"
# MAIL_PASSWORD="password"
# MAIL_DEFAULT_SENDER = "no_reply@example.org"
