version: '3.9'
services:

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database-volume:/var/lib/postgresql/data

  asreview:
    image: "ghcr.io/asreview/asreview:v1.6.1"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - project-folder:/app/project_folder
      - ./asreview_config.toml:/app/asreview_config.toml
    environment:
      - ASREVIEW_LAB_API_URL=/
      - ASREVIEW_LAB_CONFIG_PATH=/app/asreview_config.toml
      - ASREVIEW_LAB_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - ${BACKEND_EXTERNAL_PORT}:5006
    entrypoint: []
    command: >
      bash -c "asreview auth-tool create-db
      && gunicorn -w ${WORKERS} -b \"0.0.0.0:5006\" \"asreview.webapp.app:create_app()\""

  server:
    image: nginx
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:80
    volumes:
      - ./asreview.conf:/etc/nginx/nginx.conf
    depends_on:
      - asreview

volumes:
  project-folder:
  database-volume:
