version: '3.9'
services:

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database-volume:/var/lib/postgresql/data

  asreview:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - project-folder:/app/project_folder
      - ./flask_config.toml:/app/flask_config.toml
    environment:
      - WORKERS=${WORKERS}
      - ASREVIEW_LAB_API_URL=${DOMAIN}:${BACKEND_EXTERNAL_PORT}/
      - ASREVIEW_LAB_CONFIG_PATH=./flask_config.toml
      - ASREVIEW_LAB_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - ${BACKEND_EXTERNAL_PORT}:5006

  server:
    image: nginx
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:80
    volumes:
      - ./asreview.conf:/etc/nginx/nginx.conf
    depends_on:
      - asreview

volumes:
  project-folder:
  database-volume: